name: xeus-python-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn  # Covers Supervised & Unsupervised Learning
  - scipy
  - ipywidgets    # Great for interactive AI demos
