name: xeus-python-kernel
channels:
  - https://repo.prefix.dev/conda-forge  # Use this for general packages
  - https://repo.prefix.dev/emscripten-forge # Corrected path
  - conda-forge
dependencies:
  - python=3.11         # Explicitly set version
  - xeus-python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - ipywidgets
